create table EventPekerjaan (id bigint not null, createdDate datetime, deleted varchar(255), modifiedDate datetime, status integer not null, tanggal datetime not null, workOrder_id bigint not null, primary key (id))
create table ItemPakaian (id bigint not null, createdDate datetime, deleted varchar(255), modifiedDate datetime, nama varchar(50) not null, kategori_id bigint, primary key (id))
create table ItemWorkOrder (id bigint not null, createdDate datetime, deleted varchar(255), nominal decimal(19,2), pilihanPersen integer, harga decimal(19,2) not null, hargaSetelahDiskon decimal(19,2), jumlah integer not null, keterangan varchar(255), modifiedDate datetime, work_id bigint not null, workOrder_id bigint not null, primary key (id))
create table JenisWork (id bigint not null, createdDate datetime, deleted varchar(255), keterangan varchar(100), modifiedDate datetime, nama varchar(50) not null, primary key (id))
create table Kategori (id bigint not null, createdDate datetime, deleted varchar(255), keterangan varchar(100), modifiedDate datetime, nama varchar(50) not null, primary key (id))
create table Pelanggan (id bigint not null, alamat varchar(200), corporate bit not null, createdDate datetime, deleted varchar(255), modifiedDate datetime, nama varchar(50) not null, nomorTelepon varchar(50), primary key (id))
create table Pembayaran (DTYPE varchar(31) not null, id bigint not null, createdDate datetime, deleted varchar(255), keterangan varchar(50), modifiedDate datetime, tagihan decimal(19,2) not null, tanggal date not null, jumlahBayarDimuka decimal(19,2), tanggalPelunasan date, nomorKartu varchar(50), primary key (id))
create table Work (id bigint not null, createdDate datetime, deleted varchar(255), hargaCorporate decimal(19,2) not null, hargaOutsider decimal(19,2) not null, modifiedDate datetime, itemPakaian_id bigint not null, jenisWork_id bigint not null, primary key (id))
create table WorkOrder (id bigint not null, createdDate datetime, deleted varchar(255), nominal decimal(19,2), pilihanPersen integer, estimasiSelesai date, express bit not null, jumlahDiskon decimal(19,2), keterangan varchar(255), modifiedDate datetime, namaPenerima varchar(255), nomor varchar(12) not null, statusTerakhir integer not null, tanggal date not null, total decimal(19,2), pelanggan_id bigint not null, pembayaran_id bigint, primary key (id))
alter table EventPekerjaan add constraint FK_qonm5ahrj2kxc4ct2jlskby2c foreign key (workOrder_id) references WorkOrder (id)
alter table ItemPakaian add constraint FK_qhibu36etmaf6efsp6hetswq5 foreign key (kategori_id) references Kategori (id)
alter table ItemWorkOrder add constraint FK_qidm6j27256q8x9th8r27q43b foreign key (work_id) references Work (id)
alter table ItemWorkOrder add constraint FK_jsocwnor4t29jaqky7jw75u8j foreign key (workOrder_id) references WorkOrder (id)
alter table Work add constraint FK_q3gdl83u4jkkl3o3qdjggqoe9 foreign key (itemPakaian_id) references ItemPakaian (id)
alter table Work add constraint FK_c2xf386v4jfxp5hho4rcg06tl foreign key (jenisWork_id) references JenisWork (id)
alter table WorkOrder add constraint FK_fr5t4jc9nqok0k8fpt2uy5xsp foreign key (pelanggan_id) references Pelanggan (id)
alter table WorkOrder add constraint FK_2kmvja4i7gcsysw2s2m3kf8n8 foreign key (pembayaran_id) references Pembayaran (id)
create table hibernate_sequences ( sequence_name varchar(255),  sequence_next_hi_value integer )
